# Generated by Django 4.2.7 on 2024-01-15 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.IntegerField(blank=True, null=True)),
                ('nik', models.IntegerField(blank=True, null=True)),
                ('nama_alumni', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('laki-laki', 'laki-laki'), ('perempuan', 'perempuan')], max_length=20, null=True)),
                ('tgl_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('thn_lulus', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='school.school')),
                ('vocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='school.vocation')),
            ],
            options={
                'ordering': ('nama_alumni',),
            },
        ),
    ]
