# Generated by Django 4.2.7 on 2024-01-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ('nama_alumni', 'thn_lulus')},
        ),
        migrations.AlterField(
            model_name='alumni',
            name='thn_lulus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
