# Generated by Django 4.2.7 on 2023-12-31 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('alumni', 'alumni')], default='admin', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Alumnibio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.IntegerField(unique=True)),
                ('nik', models.IntegerField(blank=True, null=True, unique=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir', models.DateTimeField(blank=True, null=True)),
                ('tingkat_pendidikan', models.CharField(max_length=100, null=True)),
                ('thn_lulus', models.CharField(max_length=100, null=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumnibio', to='school.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumnibio', to=settings.AUTH_USER_MODEL)),
                ('vocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumnibio', to='school.vocation')),
            ],
            options={
                'ordering': ('thn_lulus',),
            },
        ),
    ]
