# Generated by Django 4.2.7 on 2024-01-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('staff', 'staff')], default='admin', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Alumnibio',
        ),
    ]
